name:                cclang
version:             1.0.0
github:              "rena2damas/sorted-tagged-set"
license:             MIT
author:              "Renato Damas"
maintainer:          "rena2damas@gmail.com"
copyright:           "2018 Renato Damas"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

description:         Please see the README on Github at <https://github.com/githubuser/cclang#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  cclang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cclang

tests:
  cclang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cclang
    - hspec == 2.*
    - QuickCheck
    - stack-hpc-coveralls